table Table1
	lineageTag: 0d4354ab-3427-443e-a4aa-8940dbcbf59f

	column City
		dataType: string
		lineageTag: 67cf1266-3979-4ae9-bd6d-7434170cc1cf
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Mixed
		dataType: string
		lineageTag: 17c51c18-ec2b-49cb-b957-3213bcc4ee4a
		summarizeBy: none
		sourceColumn: Mixed

		annotation SummarizationSetBy = Automatic

	column 'Num of people'
		dataType: int64
		formatString: 0
		lineageTag: 4834a435-144f-4471-bb17-31f47394eb50
		summarizeBy: sum
		sourceColumn: Num of people

		annotation SummarizationSetBy = Automatic

	partition Table1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\work\TryDB.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"City", type text}, {"Mixed", type any}, {"Num of people", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

